### ISSUE TITLE
[FEATURE]: implement repository interface for meilisearch operations

### ISSUE THREAD

**Issue by junghoon-vans** [junghoon-vans/spring-data-meilisearch#5]
In Spring Data, the `repository` are a common interface to access data storage, so we need to provide a standardized way to manipulate data that is accessible regardless of the type of data storage.

## Tasks

Implementing a repository requires the following tasks

- [x] `Repository` to manipulate data in meilisearch
- [x] Support configuration with `Spring Namespace`
- [x] Support configuration with `Annotation`
