### ISSUE TITLE
[FEATURE]: implement operations for meilisearch APIs

### ISSUE THREAD

**Issue by junghoon-vans** [junghoon-vans/spring-data-meilisearch#6]
## Description

Defines an interface for implementing the [Meilisearch APIs](https://www.meilisearch.com/docs/reference/api/overview). This is implemented using the [meilisearch-java](https://github.com/meilisearch/meilisearch-java) client.

## Tasks

Implementing a operations requires the following tasks

- [x] define `MeilisearchOperation` interface
- [x] create `MeilisearchTemplate` class to implement [methods of operations](#methods-of-operations)
- [x] support configuration with `Annotation`

## Methods of operations
- Saves an entity.
- Saves all given entities.
- Retrieves an entity by its primary key.
- Retrieves all entities of the given type.
- Retrieves all entities of the given type with the given primary keys.
- Checks whether an entity with the given primary key exists.
- Returns the number of entities available.
- Deletes the entity with the given primary key.
- Deletes a given entity.
- Deletes all entities of the given type with the given primary keys.
- Deletes the given entities.
- Deletes all entities of the given type.
